print("Hello World")
print("I am learning git and github.It's cool!")
print("I am surprised to know that github gives unlimited access to create new repositories and unlimites access to projects!")
print("It is really cool how they manages it!")
print("Visit this channel in irc to ask questions related to github:  #github")
